[GAIA-1547] Identity export
leftshiftone/gaia-sdk pull request #64
Opened 2020-11-11 13:16 UTC by LoLei

- JS
- Java (Kotlin)
- Python

E2E in gaia-global

2020-11-13 13:46 UTC, rschluesselbauer requested changes

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/identity/IdentityRef.kt
> +    override fun onError(t: Throwable?) {} //FIXME when connection is closed, but the complete file is transferred, no exception should be thrown
Wurde da was vergessen?

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/identity/IdentityRef.kt
> +                .blockingSubscribe(IdentityWriteSubscriber(filePath))
So wird das File heruntergeladen sobald export aufgerufen wird. Durch den Publisher return-Type würde man aber glauben, dass es erst passiert wenn er konsumiert (=subscribed) wird.
Man könnte zB statt blockingSubscribe reduce verwenden und als Akkumulator immer einen FileOutputStream weiter geben.

IdentityWriteSubscriber wird hier ohne FileOutputStream initialisiert - (warum) geht das?

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/__tests__/IdentityRef.test.ts
> +describe('dataref tests:', () => {
identityref

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/__tests__/IdentityRef.test.ts
> +                return ['blob'];
da sollt tatsächlich ein blob zurückkommen und net ein array mit string drinnen

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/__tests__/IdentityRef.test.ts
> +                expect(e.length).toEqual(1);
da kann man überprüfen obs wohl das gleiche blob ist was rauskommt

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/api/ISensorStream.ts
> +    identity(uri: string): IdentityRef
uri -> id

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/__tests__/IdentityRef.test.ts
> +            const observable = gaiaRef.identity('identity://mockTenant/mockIdentityReference').export();
es sollte nur die identity id angegeben werden - da gibts keine uri wie bei der data api

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/graphql/request/input/IdentitySourceRequestImpulse.ts
> +    constructor(uri: string) {
uri -> (identity)id

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/http/HttpSensorStream.ts
> +    identity(uri: string): IdentityRef {
uri -> id

id kann nullable sein, weil wir beim import dann evt die id noch nicht wissen.

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/api/IdentityRef.ts
> +        return from(this.client.postAndRetrieveBinary(new IdentitySourceRequestImpulse(this.identityId), '/identity/source')
davor bitte checken ob identityId null ist

2020-11-13 13:46 UTC, rschluesselbauer commented on gaia-sdk-python/gaia_sdk/api/IdentityRef.py
> +        response = self.client.post_json(IdentitySourceRequestImpulse(self.identity_id), "/identity/source").content
ich weiß, dass das in DataRef auch so drinnen ist (vermutlich wegen mir).
Wäre aber appreciated wenn wir das auf async umstellen können, damit erst exportiert wird, wenn das Observable konsumiert wird.
Beispiel dafür ist in der SkillRef. 
`        return rx.from_callable(
            lambda: self._client.post_json(request, url_postfix="/skill/evaluate"),
            self._scheduler) \
            .pipe(
            ops.map(lambda response: json.loads(response.content)),
            ops.map(lambda d: SkillEvaluation(d)))`

Dazu musst halt vom HttpSensorStream den scheduler weitergeben.
Wenns leicht geht bitte auch beim Download der DataApi in Python ausbessern (sonst halt Bug anlegen).

2020-11-16 06:55 UTC, alberto-ls1 commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/identity/IdentityRef.kt
> +                .blockingSubscribe(IdentityWriteSubscriber(filePath))
Da hat @LoLei  leider mein Code von dataRef 1:1 übernommen :-(. Ich habs grad auf dataRef nachgebessert. bitte @LoLei dataRef.kt updaten und identityRef.kt dementsprechend anpassen.

2020-11-16 06:55 UTC, alberto-ls1 commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/identity/IdentityRef.kt
> +    override fun onError(t: Throwable?) {} //FIXME when connection is closed, but the complete file is transferred, no exception should be thrown
Da hat @LoLei  leider mein Code von dataRef 1:1 übernommen :-(. Ich habs grad auf dataRef nachgebessert. bitte @LoLei dataRef.kt updaten und identityRef.kt dementsprechend anpassen.

2020-11-16 14:44 UTC, rschluesselbauer requested changes

2020-11-16 14:44 UTC, rschluesselbauer commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/identity/IdentityOp.kt
> +                .reduce(FileOutputStream(filePath), { result: FileOutputStream, nextBytes: ByteArray ->
Des schaut gut aus, aber im error case müsste der FileOutputStream geschlossen werden denke ich.

2020-11-16 14:47 UTC, rschluesselbauer commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/identity/IdentityOp.kt
> +                .reduce(FileOutputStream(filePath), { result: FileOutputStream, nextBytes: ByteArray ->
Und man sollt whs reduceWith verwenden - da kann man dann statt FileOutputStream(filePath) eine Function übergeben: { FileOutputStream(filePath) }

2020-11-16 16:34 UTC, rschluesselbauer approved these changes

2020-11-17 07:18 UTC, merged