feature/GAIA-2326
leftshiftone/gaia-sdk pull request #75
Opened 2020-11-30 06:45 UTC by Manzn

Data Upload Progress

2020-11-30 12:03 UTC, rschluesselbauer requested changes

2020-11-30 12:03 UTC, rschluesselbauer commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/data/DataRef.kt
>          val upload = DataUpload.create(concatUri(this.uri, fileName), content, override)
(gilt für alle Implementierungen)

2020-11-30 12:03 UTC, rschluesselbauer commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/data/DataRef.kt
> +    fun onUploadProgress(progress: Long);
progress wird immer zwischen 0 und 100 sein, oder?
Ist da ein int oder ein float sinnvoller?

2020-11-30 14:41 UTC, Manzn commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/data/DataRef.kt
> +                    val progress = (100 * (it.ordinal)) / this.totalNumberOfChunks
ja

2020-11-30 14:43 UTC, Manzn commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/data/DataRef.kt
> +    fun onUploadProgress(progress: Long);
wird gerundet und ist immer zwischen 0 - 100

2020-11-30 15:35 UTC, rschluesselbauer submitted a review, later dismissed

2020-12-01 08:04 UTC, rschluesselbauer approved these changes

2020-12-01 11:33 UTC, rschluesselbauer approved these changes

2020-12-01 11:34 UTC, merged