Feature/gaia 2340
leftshiftone/gaia-sdk pull request #80
Opened 2020-12-14 14:36 UTC by Manzn

JS part done
JAVA part done
PYTHON part in progress

2020-12-15 09:30 UTC, rschluesselbauer requested changes

2020-12-15 09:30 UTC, rschluesselbauer commented on gaia-sdk-java/gaia-sdk-core/src/test/kotlin/gaia/sdk/core/IdentityTest.kt
> +        configureStub("Bearer", errorCode = 200, responseFile = "ok_data_upload_response.json", uri = "/api/identity/import")
Absicht dass hier auch "ok_data_upload_response.json" kommt?

2020-12-15 09:30 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/__tests__/IdentityOp.test.ts
> +        // FIXME empty Blob -> cross-blob always empty???
Funktioniert das mit crossblob nicht richtig?

2020-12-15 09:30 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/api/DataRef.ts
> +export class DataUpload {
Nicht nötig

2020-12-15 09:30 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/api/IdentityOp.ts
> +        const upload = DataUpload.create(uri, content, override);
wieder einfach DataRef.add verwenden bitte

2020-12-15 09:30 UTC, rschluesselbauer commented on gaia-sdk-python/gaia_sdk/api/IdentityOp.py
> +CHUNK_SIZE = 1024 * 1024 * 5
Bitte das entfernen und DataRef.add verwenden

2020-12-15 09:30 UTC, rschluesselbauer commented on gaia-sdk-python/gaia_sdk/api/IdentityOp.py
> +        new_file_data_ref = DataUpload(file_uri, content, number_of_chunks, override) \
Hier DataRef.add verwenden

2020-12-15 09:30 UTC, rschluesselbauer commented on gaia-sdk-python/gaia_sdk/api/IdentityOp.py
> +        self.complete_import(file_uri, tenant_id, identity_name, True, identity_id)
mit dem observable von DataRef.add arbeiten, so dass der Import asynchron implementiert ist.
also zB
`return dataRef.add(...).pipe(
            ops.flat_map(lambda response: self.complete_import(....)),
            ops.do_on_next(lambda next: self._logger.debug("Finished import of identity with id ... to tenant ...")))`

Das do_on_next is eher Pseudocode - weiß nicht genau wie das in python aussieht

2020-12-15 09:30 UTC, rschluesselbauer commented on gaia-sdk-python/gaia_sdk/tests/test_identity_ref.py
> +            return MockResponse("asdfqwer")
Wie kommt bei dem oberen Test die richtige Uri raus ("gaia://tenantId/identities/identityName") wenn wir hier nur "asdfqwer" ausgeben?

2020-12-15 11:03 UTC, Manzn commented on gaia-sdk-javascript/src/__tests__/IdentityOp.test.ts
> +        // FIXME empty Blob -> cross-blob always empty???
der ist immer leer. hab da noch nichts funktionierendes gefunden...

2020-12-16 08:26 UTC, rschluesselbauer commented on gaia-sdk-java/gaia-sdk-api/src/main/kotlin/gaia/sdk/api/identity/IdentityOp.kt
> +                    it
map {it} ist redundant - tut also nix weil it is ja eh schon das was vom Flowable daherkommt.
doOnError schluckt den Wert nicht, keine Sorge :-)

2020-12-16 08:38 UTC, rschluesselbauer commented on gaia-sdk-javascript/src/api/IdentityOp.ts
> +        return from(new DataRef(`gaia://${tenantId}/identities/`, this.client)
Da musst du mit RX arbeiten und nicht mit Promises.

Ein RX Observable wird erst dann konsumiert wenn jemand subscribe (o.ä.) aufruft.
Eine Promise wird zwar async aber sofort konsumiert.

Was du also willst ist whs ca so etwas:
`new DataRef(`gaia://${tenantId}/identities/`, this.client)
.add(file.name, content, override)
.pipe(mergeMap(dataRef => from(this.importIdentity(dataRef.getUri(), tenantId, identityName, override, identityId).catch(reason => {
                throw new Error('Identity Upload failed: ' + reason);
            }))))
`

2020-12-16 08:48 UTC, rschluesselbauer commented on gaia-sdk-python/gaia_sdk/api/IdentityOp.py
> +CHUNK_SIZE = 1024 * 1024 * 5
bump

2020-12-16 08:50 UTC, rschluesselbauer commented on gaia-sdk-python/gaia_sdk/api/IdentityOp.py
> +        uri = "gaia://{}/identities/".format(tenant_id)
Zur Info, man kann in Python noch gemütlicher Variablen in Strings einbauen wenn man ein f vor die Quotes schreibt.
some_var = f"value of tenant_id: {tenant_id}"

2020-12-16 09:01 UTC, rschluesselbauer approved these changes

2020-12-16 09:34 UTC, merged